### ISSUE TITLE
Facing a problem with module

### ISSUE THREAD

**Issue by freakingfab** [bradtraversy/coindex-cli#8]
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Daksh\OneDrive\Desktop\webd\coindex-CLI2\node_modules\configstore\index.js from C:\Users\Daksh\OneDrive\Desktop\webd\coindex-CLI2\lib\KeyManager.js not supported.
Instead change the require of index.js in C:\Users\Daksh\OneDrive\Desktop\webd\coindex-CLI2\lib\KeyManager.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\Daksh\OneDrive\Desktop\webd\coindex-CLI2\lib\KeyManager.js:1:19)
    at Object.<anonymous> (C:\Users\Daksh\OneDrive\Desktop\webd\coindex-CLI2\commands\key.js:3:20)
    at Object.<anonymous> (C:\Users\Daksh\OneDrive\Desktop\webd\coindex-CLI2\bin\coindex-key.js:2:13) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by Kimkykie** [comment]
Hello,

You might have to switch to **version 5** of configstore, **version 6** which is the latest version is now an ESM.

The other option is esm enabling, you can find the guide here [ESM enabling](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling). I hope this helps.
